/** @format */

export enum actionTypes {
	GET_SHOES = "GET_SHOES",
	GET_SHOES_SUCCESS = "GET_SHOES_SUCCESS",
	GET_SHOES_ERROR = "GET_SHOES_ERROR",
	ADD_TO_CART = "ADD_TO_CART",
	ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS",
	ADD_TO_CART_ERROR = "ADD_TO_CART_ERROR",
	ADD_TO_LIKED = "ADD_TO_LIKED",
	ADD_TO_LIKED_SUCCESS = "ADD_TO_LIKED_SUCCESS",
	ADD_TO_LIKED_ERROR = "ADD_TO_LIKED_ERROR",
	REMOVE_FROM_CART = "REMOVE_FROM_CART",
	CLEAR_CART = "CLEAR_CART",
}
